name: scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm i

    - name: Lint source and tests
      run: npm run lint
    - name: Unit test smart contracts
      run: npm test
    - name: Coverage report
      run: npm run coverage
    # - name: Coveralls
      # uses: coverallsapp/github-action@master
      # with:
        # github-token: ${{ secrets.GITHUB_TOKEN }}
