name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm i

    - name: Lint source and tests
      run: npm run lint
    - name: Unit test smart contracts
      run: npm test
    - name: Coverage report
      run: npm run coverage
    # - name: Coveralls
      # uses: coverallsapp/github-action@master
      # with:
        # github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Slither Static Analysis
      uses: luisfontes19/slither-static-analysis-action@v0.3.2
      with:
        slither-version: '0.6.13'
        run-npm-install: false
        high-threshold: 1
        medium-threshold: 1
        low-threshold: 3
        optimization-threshold: 5
        informative-threshold: 10
        projectPath: "."
