name: scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Slither Static Analysis
      uses: luisfontes19/slither-static-analysis-action@v0.3.2
      with:
        slither-version: '0.7.1'
        run-npm-install: true
        high-threshold: 1
        medium-threshold: 1
        low-threshold: 3
        optimization-threshold: 5
        informative-threshold: 10
        projectPath: "."
